#define _GNU_SOURCE
/* config.h.  Generated by configure.  */
/* config.h.in.  Modified automatically by autoheader.  */
/* This is a header file containing site-specific preprocessor macro
   definitions for compiling the ANA program. LS 9mar99. */
/* $Header: /usr/local/cvsroot/ana/config.h.in,v 4.0 2001/01/22 21:56:39 strous Exp $ */

/* Define to empty if the keyword does not work.  */
/* #undef const */

/* Define if you have the ANSI C header files.  */
#define STDC_HEADERS 1

/* Define if your processor stores words with the most significant
   Byte first (like Motorola and SPARC, unlike Intel and VAX).  */
/* #undef WORDS_BIGENDIAN */

/* The number of bytes in a long int64_t.  */
#define SIZEOF_LONG_LONG_INT 8

/* The number of bytes in a unsigned char.  */
#define SIZEOF_UNSIGNED_CHAR 1

/* The number of bytes in a uint16_t.  */
#define SIZEOF_UNSIGNED_SHORT_INT 2

/* Define if you have the <regex.h> header file. */
/* #undef HAVE_REGEX_H */

/* Define if you have the <sys/mtio.h> header file (non-POSIX). */
#define HAVE_SYS_MTIO_H 1

/* Define if you have the X11 library (-lX11).  */
#define HAVE_LIBX11 1

/* Define if you have the Xt library (-lXt).  */
/* #undef HAVE_LIBXT */

/* Define if you have the c library (-lc).  */
#define HAVE_LIBC 1

/* Define if you have the jpeg library (-ljpeg).  */
#define HAVE_LIBJPEG 1

/* Define if you have the m library (-lm).  */
#define HAVE_LIBM 1

/* Define equal to (1.0/0.0) if you can divide 1.0 by 0.0 */
#define INFTY (1.0/0.0)

#define SOFA 1

/* variable attributes are gcc specific.  LS 9mar99 */
#ifndef __GNUC__
#define __attribute__(x)
#endif

/* user-selectable packages */
/* enable debugger routines */
/* #undef DEBUG */

/* enable development routines */
#define DEVELOP 1

/* enable Motif routines */
/* #undef MOTIF */

/* include X11 stuff */
#define X11 1

/* include JPEG stuff */
#if HAVE_LIBJPEG
#define JPEG 1
#endif

/* bison debugging */
/* #undef YYDEBUG */

/* platform identification */
#define PLATFORM "i686-pc-linux-gnu"


