W[1]:w[1];
M[1]:x[1];
S[1]:0;
X[1]:0;
W[k]:=W[k-1]+w[k];
X[k]:=X[k-1]+w[k]*w[k];
M[k]:=ratsimp(M[k-1]+(x[k]-M[k-1])*w[k]/W[k]);
S[k]:=ratsimp(S[k-1]+(x[k]-M[k-1])*(x[k]-M[k])*w[k]);
sumx[k]:=sum(x[i]*w[i],i,1,k);
sumxx[k]:=sum(x[i]*x[i]*w[i],i,1,k);
v[k]:=ratsimp(sumxx[k]-sumx[k]^2/W[k]);
/* S[k] = weighted sum of squares, target algorithm */
/* v[k] = weighted sum of squares, naive algorithm */
popsdev[k]:=ratsimp(sqrt(S[k]/W[k]));
sampsdev[k]:=ratsimp(sqrt(S[k]*W[k]/(W[k]*W[k] - X[k])));
