* To E
** Elliptic Orbit
   
   e < 1
 
   M = E - e sin E

   M  ≡ M′√|δ|³
   M′ ≡ M/√|δ|³
   E  ≡ E′√|δ|
   δ  ≡ e - 1

   The case E ≫ 1 is not relevant, because E and M repeat modulo 2π,
   so E ≪ 1.

   E ≪ 1 ∴ sin(E) ≈ E - ⅙E³

   M ≈ E - e(E - ⅙E³)
     = E - eE + ⅙eE³
     = |δ|E + ⅙eE³

   M′ = M/√|δ|³
      ≈ (E/√|δ|) + ⅙e(E/√|δ|)³

*** When does the first-order term dominate?
   (E/√|δ|) ≫ ⅙e(E/√|δ|)³
     ⇔ 1 ≫ ⅙e(E/√|δ|)²
     ⇔ (E/√|δ|)² ≪ 6/e
     ⇔ E/√|δ| ≪ √(6/e)
     ⇔ E ≪ √(6|δ|/e)

   So the first-order term dominates when E ≪ √(6|δ|/e) and the
   third-order term dominates when E ≫ √(6|δ|/e).

*** E ≪ 1 ∧ first-order term dominates

    E ≪ √(6|δ|/e)
      ∴ M′ ≈ E/√|δ|
      ∴ E ≈ M′√|δ| = M/|δ|

*** What is the range of M′?

    E ≪ 1
      ∴ M′ ≪ 1/√|δ|

    E ≪ √(6|δ|/e)
      ∴ M′ = E/√|δ| ≪ √(6/e)

    1/√|δ| > √(6/e)
      ⇔ |δ| < ⅙e
      ⇔ |δ| < ⅙ (approximately) ∧ e ≈ 1

    e ≈ 1
      ⇔ 1/√|δ| > √(6/e)
      ⇒ M′ ≪ √(6/e)

    e < ⅚
      ⇔ √(6/e) > 1/√|δ|
      ⇒ M′ ≪ 1/√|δ|

*** E ≪ 1 ∧ E′ ≫ √(6/e)

    E′ ≫ √(6/e)
      ∴ ⅙eE′³ ≫ E′
      ∴ M′ ≈ ⅙eE′³ = ⅙eE³/√|δ|³
      ∴ E′ ≈ (6M′/e)^⅓
      ∴ E ≈ (6M′/e)^⅓ √|δ|

*** What is the range of M′?
    
    E ≪ 1
      ∴ (6M′/e)^⅓ √|δ| ≪ 1
      ∴ 6M′/e ≪ 1/√|δ|³
      ∴ M′ ≪ ⅙e/√|δ|³

    E′ ≫ √(6/e)
      ∴ (6M′/e)^⅓ ≫ √(6/e)
      ∴ 6M′/e ≫ √(6/e)³
      ∴ M′ ≫ √(6/e)

    √(6/e) < ⅙e/√|δ|³
      ⇔ 6/e < (1/6²)e²/|δ|³
      ⇔ e³/|δ|³ > 6³
      ⇔ e/|δ| > 6
      ⇔ |δ| < ⅙e
      ⇔ |δ| < ⅙ (approximately)

    So this case is only possible if |δ| < ⅙ (approximately).
** Hyperbolic Orbit

   e > 1

   M = e sinh E - E

   M  ≡ M′√|δ|³
   M′ ≡ M/√|δ|³
   δ  ≡ e - 1

*** E ≪ 1

    E ≪ 1 ∴ sinh(E) ≈ E + ⅙E³

    M ≈ e(E + ⅙E³) - E
      = |δ|E + ⅙eE³

    M′ = M/√|δ|³
      ≈ (E/√|δ|) + ⅙e(E/√|δ|)³
      = E′ + ⅙eE′³

    The last formulas for M and M′ are identical to those for
    elliptical orbits.

**** When does the first term dominate?

     The derivation is identical to that for elliptical orbits.

     So E′ ≫ ⅙eE′³ if E′ ≪ √(6/e), and ⅙eE′³ ≫ E′ if E′ ≫ √(6/e).

**** E ≪ 1 ∧ E′ ≪ √(6/e)

     The derivation is identical to that for elliptical orbits.

     M′ ≈ E′ = E/√|δ|
     E ≈ M′√|δ|

**** What is the range of M′?

     The derivation is analogous to that for elliptical orbits.

     M′ ≪ 1/√|δ| ∧ M′ ≪ √(6/e)

     e ≈ 1 ⇒ M′ ≪ √(6/e)

     e > 7/6 ⇒ M′ ≪ 1/√|δ|

**** E ≪ 1 ∧ E′ ≫ √(6/e)

     The derivation is identical to that for elliptical orbits.

     M′ ≈ ⅙eE³/√|δ|³
     E ≈ (6M′/e)^⅓ √|δ|

**** What is the range of M′?

     The derivation is identical to that for elliptical orbits.
     
     M′ ≪ ⅙e/√|δ|³
     ∧ M′ ≫ √(6/e)
     ∧ |δ| < ⅙ (approximately)

     So this case is only possible if |δ| < ⅙ (approximately).
*** E ≫ 1

    E ≫ 1 ∴ sinh(E) ≈ ½ sgn(E) exp(|E|)

    E ≫ 1 ∴ e sinh E ≫ E

    M ≈ ½e sgn(E) exp(|E|)
     ∴ E ≈ sgn(M) log(2|M|/e)
         = sgn(M′) log(2|M′|√|δ|³/e)

    Instead use

    E ≈ sgn(M′) log(1 + 2|M′|√|δ|³/e)

    so the log(…) value remains positive.  For large arguments the
    result is asymptotically the same as for the original formula.

**** What is the range of M′?

     E ≫ 1
     ∴ log(1 + 2|M′|√|δ|³/e) ≫ 1
     ∴ 2|M′|√|δ|³/e ≫ 1
     ∴ M′ ≫ ½e/√|δ|³
** Summary

   1. M′ ≪ √(6/e) ∧ M′ ≪ 1/√|δ| ⇒ E ≈ M′√|δ| ∧ E ≪ 1
   2. √(6/e) ≪ M′ ≪ ⅙e/√|δ|³ ∧ |δ| < ⅙ ⇒ E ≈ (6M′/e)^⅓ √|δ| ∧ E ≪ 1
   3. M′ ≫ ½e/√|δ|³ ⇒ E ≈ sgn(M′) log(1 + 2|M′|√|δ|³/e) ∧ E ≫ 1

* To ν
** Case 1

   M′ ≪ √(6/e) ∧ M′ ≪ 1/√|δ| ⇒ E ≈ M′√|δ| ∧ E ≪ 1

   e ≪ 1 ⇒ M′ ≪ 1/√|δ|
   δ ≪ 1 ⇒ M′ ≪ 1/√e

   E ≪ 1 ∴ tan(½E) ≈ ½E

   e < 1
   ⇒ tan(½ν) = √((1+e)/(1-e)) tan(½E)
             ≈ √((1+e)/(1-e)) ½E

   e ≪ 1 ⇒ √((1+e)/(1-e)) ≈ 1+e
    ⇒ tan(½ν) ≈ ½(1+e)E ≈ ½(1+e)M′√|δ| ≈ M′√|δ| ≪ 1
   tan(½ν) ≪ 1 ⇒ ν ≈ 2 tan(½ν) ≈ (1+e)M′√|δ| ≈ 2M′√|δ| ≪ 1

   δ ≪ 1 ⇒ √((1+e)/(1-e)) = √((2+δ)/|δ|) ≈ √|2/δ|
    ⇒ tan(½ν) ≈ E/√|2δ| ≈ M′/√2 ≪ 1/√|δ| ≫ 1
   tan(½ν) = t ≫ 1 ⇒ ν ≈ sgn(t) (π - 2/|t|)

   M′ ≪ 1 ⇒ ν ≈ 2 tan(½ν) ≈ M′√2
   M′ ≫ 1 ⇒ ν ≈ sgn(M′) (π - (√8)/M′)

** Case 2

   √(6/e) ≪ M′ ≪ ⅙e/√|δ|³ ∧ |δ| < ⅙ ⇒ E ≈ (6M′/e)^⅓ √|δ| ∧ E ≪ 1

   e ≪ 1 ⇒ tan(½ν) ≈ ½(1+e)E ≈ ½(1+e)(6M′/e)^⅓ √|δ| ≪ 1
   ⇒ ν ≈ (1+e)(6M′/e)^⅓ √|δ| ≪ 1

   δ ≪ 1 ∧ e < 1 ⇒ tan(½ν) ≈ E/√|2δ| ≈ (6M′/e)^⅓ /√2

   E ≪ 1 ⇒ tanh(½E) ≈ ½E

   δ ≪ 1 ∧ e > 1
   ⇒ tan(½ν) = √((e+1)/(e-1)) tanh(½E)
     ≈ √|2/δ| ½E = E/√|2δ| ≈ (6M′/e)^⅓ /√2

   (6M′/e)^⅓ /√2 ≪ 1
   ⇔ M′ ≪ ⅙e√8 = ⅓e√2 ≈ e

   M′ ≪ e ⇒ ν ≈ 2 tan(½ν) ≈ (6M′/e)^⅓ √2
   M′ ≫ e ⇒ ν ≈ sgn(t)(π-2/|t|) = sgn(M′)(π - √8(e/6M′)^⅓)

** Case 3

   M′ ≫ ½e/√|δ|³ ⇒ E ≈ log(2|M′|√|δ|³/e) ∧ E ≫ 1

   E ≫ 1 ⇒ tanh(½E) ≈ sgn(E)(1 - 2 exp(-|E|))

   δ ≪ 1 ⇒ √((e+1)/(e-1)) = √|2/δ|
    ⇒ tan(½ν) ≈ √|2/δ| sgn(E)(1 - 2 exp(-|E|))
    ≈ √|2/δ| sgn(M′) (1 - 2 exp(-log(2|M′|√|δ|³/e)))
    = √|2/δ| sgn(M′) (1 - e/(|M′|√|δ|³)) ≈ √|2/δ|

   M′ ≫ ½e/√|δ|³ ⇒ e/(|M′|√|δ|³) ≪ 1

   e ≫ 1 ⇒ √((e+1)/(e-1)) ≈ 1 + 1/e ≈ 1
    ⇒ tan(½ν) ≈ (1+1/e)(1 - 2exp(-|E|))
    ≈ (1+1/e)(1 - e/(|M′|√|δ|³)) ≈ 1+1/e
** Parabolic orbit

   For a parabolic orbit,

   W = M′√(9/8)
   u = (W + √(W² + 1))^⅓
   tan(½ν) = u - 1/u

   M′ ≪ 1 ⇒ tan(½ν) ≈ ⅔W = M′/√2

   M′ ≫ 1 ⇒ tan(½ν) ≈ (2W)^⅓ = (3M′/√2)^⅓

** Summary

   1) M′ ≪ √(6/e) ∧ M′ ≪ 1/√|δ| ⇒ E ≈ M′√|δ| ∧ E ≪ 1
      1) e ≪ 1 ⇒ tan(½ν) ≈ (1+e)M′√|δ| ≪ 1
      2) δ ≪ 1 ⇒ tan(½ν) ≈ M′/√2
   2) √(6/e) ≪ M′ ≪ ⅙e/√|δ|³ ∧ |δ| < ⅙ ⇒ E ≈ (6M′/e)^⅓ √|δ| ∧ E ≪ 1
      2) δ ≪ 1 ⇒ tan(½ν) ≈ (6M′/e)^⅓ /√2
   3) M′ ≫ ½e/√|δ|³ ⇒ E ≈ sgn(M′) log(1 + 2|M′|√|δ|³/e) ∧ E ≫ 1
      1) δ ≪ 1 ⇒ tan(½ν) ≈ √|2/δ| sgn(M′) (1 - e/(|M′|√|δ³|))
      2) e ≫ 1 ⇒ tan(½ν) ≈ sgn(M′) (1+1/e)(1 - e/(|M′|√|δ³|))
* Meer

  d₁ = |M + e sin(E₁) - E₁|
  ρ = |2(1 - e cos(E₁))/(e sin(E₁))|
  q = d₁/ρ = |(M + e sin(E₁) - E₁)(e sin(E₁)/2(1 - e cos(E₁))|

  | e   |                              |
  |-----+------------------------------|
  | « 1 | min(s₁,s₂)                   |
  | <~1 | min(s₁,s₂)                   |
  | >~1 | M < e: min(s₁,s₂); M > e: s₃ |
  | » 1 | M < e: min(s₁,s₂); M > e: s₃ |

** Radius

   q = a(1 - e) ⇔ a = q/(1 - e)

   cos ν = (1 - t²)/(1 + t²)
   t² = (1 - cos ν)/(1 + cos ν)

   r = a(1 - e²)/(1 + e cos ν) = q (1 + e)/(1 + e cos ν)
   = q (1 + e) (1 + t²)/(1 + e + t² - e t²)
   = q (1 + e) (1 + t²)/(1 + e + (1 - e)t²)

   ellipse:
   
   t² = tan²(½ν) = ((1+e)/(1-e)) tan²(½E)
      = ((1+e)/(1-e)) (1-cos(E))/(1+cos(E))

   r = q (1 - e cos E)/(1 - e)

   hyperbola:

   t² = tan²(½ν) = ((e+1)/(e-1)) tanh²(½E)
      = ((e+1)/(e-1)) (cosh(E)-1)/(cosh(E)+1)

   r = q (e cosh E - 1)/(e - 1)

   t₃ = tanh(½E)
   cosh(E) = (1 + t₃²)/(1 - t₃²)
   sinh(E) = 2t₃/(1 - t₃²)
   tanh(E) = 2t₃/(1 + t₃²)
   t₃² = (cosh(E) - 1)/(cosh(E) + 1)

** Near-Parabolic Orbits

   M ≪ √(δ³/e) ∧ M ≪ δ ⇒ E ≈ M/|δ|
   δ ≪ 1 ⇒ tan(½ν) ≈ M/√(2|δ|³) = M′/√2

   δ^{3/2} ≪ M ≪ 1 ∧ δ ≪ 1 ⇒ E ≈ (6M)^⅓
   tan(½ν) ≈ (6M)^⅓/√(2|δ|) = (6M′)^⅓/√2

   Calculate tan(½ν) with formula for parabolic orbits, but for M′
   (1 + f) instead of for M′, with M′ ≪ 1 ⇒ find M′/√2 + M′f/√2
   = M′/√2 (1 + f)

   Same, but for M′ ≫ 1 ⇒ find (3M′/√2)^⅓ + M′^⅓ f/(2^{7/6} 3^{2/3})


   A near-parabolic hyperbolic orbit is approximated well by a
   parabolic orbit for M ≪ 1.  If |δ|^{3/2} ≪ M ≪ 1 then E ≈ (6M)^⅓.
   Then for a near-parabolic elliptic orbit, r = q (1 - e cos E)/(1 -
   e) = q (1 - (1 - |δ|) cos 1)/|δ| = q (1 - cos(1) + |δ| cos(1))/|δ|
   ≈ q (0.46 + 0.54|δ|)/|δ| = q (0.54 + 0.46/|δ|).  And for a
   near-parabolic hyperbolic orbit, r = q (e cosh(E) - 1)/(e - 1) = q
   ((1 + δ) cosh(1) - 1)/δ ≈ q (cosh(1) - 1 + δ cosh(1))/δ ≈ q (1.54 +
   0.54/|δ|).

   t(M′,e)
   t(M′,1-|δ|) ≈ t(M′(1-¼|δ|),1)  for M′ ≪ 1
   t(M′,1+|δ|) ≈ t(M′(1+¼|δ|),1)
   t(M′,1+δ) ≈ t(M′(1+¼δ),1)
