#!/bin/sh
# A script to produce C include file version.h that defines macro
# GIT_VERSION that holds (in the form of a literal string) the version
# number according to git.
pwd
if command -v git > /dev/null; then # we found git
  gv=`git describe --tags --dirty`
else				# no git found
  gv="unknown-version"
fi
echo "/*
  This file was generated by version.sh.
  Call from .git/hooks/post-commit to update at every commit.
  Try \"git help hooks\" for more information about git hooks.
*/" > new-version.h
echo "#define GIT_VERSION \"$gv\"" >> new-version.h
if diff -q new-version.h version.h > /dev/null 2>&1; then
  # the new version is the same as the old one; keep the old one
  # so no rebuild is done
  rm new-version.h
else
  # the new version is different from the old one; replace the old one
  mv new-version.h version.h
fi


